# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
print("Numpy version: ", np.__version__)

print("Numpy configuration:")
np.show_config()



Numpy version:  2.2.3
Numpy configuration:
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30158",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.12",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30158",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-u8afkksu/cp313-win_amd64/build/venv/Lib/site-packages/s

c:\Users\Arturo\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [8]:
### [your code here]
''' Random values between 0 and 1
'''
a = np.random.rand(2, 3, 5) 
a


array([[[0.64652298, 0.96747816, 0.51009013, 0.87842645, 0.12751857],
        [0.19454007, 0.40929317, 0.07564629, 0.66452807, 0.87204928],
        [0.15079483, 0.57419864, 0.67118311, 0.87038506, 0.88322964]],

       [[0.72988997, 0.42693815, 0.0825751 , 0.98622301, 0.72978042],
        [0.2419405 , 0.00441819, 0.72671706, 0.22519869, 0.8837047 ],
        [0.61080498, 0.8326278 , 0.99454578, 0.06832166, 0.42085101]]])

In [10]:
### [your code here]
''' Random values from a normal distribution center in 0 and 1 std
'''
a = np.random.randn(2, 3, 5) 
a

array([[[ 0.33121862, -0.08030494, -1.19879716,  1.05883102,
          0.87518648],
        [-0.89627103,  0.53735949, -2.04242423, -1.23707747,
          1.32675379],
        [ 0.39082175,  0.19366701, -0.46982736, -0.72421126,
          0.91331881]],

       [[-0.17908915,  1.06867796,  0.17575576,  0.29469294,
         -0.19829529],
        [-1.72228154,  0.3842897 ,  0.19089873, -1.1133846 ,
          0.14041879],
        [ 0.10355007,  1.13414164, -0.32687853, -0.27037992,
         -0.83633066]]])

In [11]:
### [your code here]
''' Random values(int) in an specific range
'''
a = np.random.randint(1, 100, (2, 3, 5)) 
a

array([[[26, 57, 18, 48, 13],
        [78, 49, 99, 16, 66],
        [93, 61,  5, 37, 28]],

       [[66, 77,  7, 30, 20],
        [41, 32, 85, 83, 36],
        [78,  8, 82,  4, 42]]], dtype=int32)


### 4. Print a.


In [12]:
### [your code here]
a


array([[[26, 57, 18, 48, 13],
        [78, 49, 99, 16, 66],
        [93, 61,  5, 37, 28]],

       [[66, 77,  7, 30, 20],
        [41, 32, 85, 83, 36],
        [78,  8, 82,  4, 42]]], dtype=int32)

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [25]:
### [your code here]
b = np.ones((5, 2, 3))
# This print 1 as a float


In [29]:
b = np.full((5, 2, 3), 1)


### 6. Print b.


In [30]:
### [your code here]
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [31]:
### [your code here]

print("Size of a:", a.size)
print("Size of b:", b.size)
print("Do a and b have the same size?", a.size == b.size)

Size of a: 30
Size of b: 30
Do a and b have the same size? True



### 8. Are you able to add a and b? Why or why not?


In [32]:
### [your code here]

try:
    c = a + b
    print("They can be added")
except ValueError as e:
    print("Error:", e)



Error: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [36]:
### [your code here]

c = np.transpose(b, (1, 2, 0))
c


array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [42]:
### [your code here]

try:
    d = a + c
    print("They can be added")
except ValueError as e:
    print("Error:", e)

print("Now they can be aded because they have the same shape")
d

They can be added
Now they can be aded because they have the same shape


array([[[ 27,  58,  19,  49,  14],
        [ 79,  50, 100,  17,  67],
        [ 94,  62,   6,  38,  29]],

       [[ 67,  78,   8,  31,  21],
        [ 42,  33,  86,  84,  37],
        [ 79,   9,  83,   5,  43]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [43]:
### [your code here]
a



array([[[26, 57, 18, 48, 13],
        [78, 49, 99, 16, 66],
        [93, 61,  5, 37, 28]],

       [[66, 77,  7, 30, 20],
        [41, 32, 85, 83, 36],
        [78,  8, 82,  4, 42]]], dtype=int32)

In [52]:
d

array([[[ 27,  58,  19,  49,  14],
        [ 79,  50, 100,  17,  67],
        [ 94,  62,   6,  38,  29]],

       [[ 67,  78,   8,  31,  21],
        [ 42,  33,  86,  84,  37],
        [ 79,   9,  83,   5,  43]]])

In [47]:
print("Each element of d is equal to each element of a plus 1, since all the elements from b where equal to 1")

Each element of d is equal to each element of a plus 1, since all the elements from b where equal to 1



### 12. Multiply a and c. Assign the result to e.


In [48]:
### [your code here]

try:
    e = a * c
    print("They can be multiply")
except ValueError as e:
    print("Error:", e)

They can be multiply


In [49]:
e

array([[[26, 57, 18, 48, 13],
        [78, 49, 99, 16, 66],
        [93, 61,  5, 37, 28]],

       [[66, 77,  7, 30, 20],
        [41, 32, 85, 83, 36],
        [78,  8, 82,  4, 42]]])



### 13. Does e equal to a? Why or why not?


In [50]:
### [your code here]

print("Yes e is equal to a since each element of a is multiply by an array of elements equal to 1")

Yes e is equal to a since each element of a is multiply by an array of elements equal to 1




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [53]:
### [your code here]

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

100
5
47.166666666666664



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [69]:
### [your code here]

f =np.empty_like(d)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [70]:
### [your code here]
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_min:
                f[i, j, k] = 0
            elif value == d_max:
                f[i, j, k] = 100
            elif value == d_mean:
                f[i, j, k] = 50
            elif d_min < value < d_mean:
                f[i, j, k] = 25
            elif d_mean < value < d_max:
                f[i, j, k] = 75

f

array([[[ 25,  75,  25,  75,  25],
        [ 75,  75, 100,  25,  75],
        [ 75,  75,  25,  25,  25]],

       [[ 75,  75,  25,  25,  25],
        [ 25,  25,  75,  75,  25],
        [ 75,  25,  75,   0,  25]]])





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [57]:
### [your code here]
d

array([[[ 27,  58,  19,  49,  14],
        [ 79,  50, 100,  17,  67],
        [ 94,  62,   6,  38,  29]],

       [[ 67,  78,   8,  31,  21],
        [ 42,  33,  86,  84,  37],
        [ 79,   9,  83,   5,  43]]])

In [58]:
f

array([[[ 25,  75,  25,  75,  25],
        [ 75,  75, 100,  25,  75],
        [ 75,  75,  25,  25,  25]],

       [[ 75,  75,  25,  25,  25],
        [ 25,  25,  75,  75,  25],
        [ 75,  25,  75,   0,  25]]])

In [59]:
print("I have the expected values")

I have the expected values


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [66]:
### [your code here]

g =np.empty_like(d, dtype=object)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_min:
                g[i, j, k] = "A"
            elif value == d_max:
                g[i, j, k] = "E"
            elif value == d_mean:
                g[i, j, k] = "C"
            elif d_min < value < d_mean:
                g[i, j, k] = "B"
            elif d_mean < value < d_max:
                g[i, j, k] = "D"

g

array([[['B', 'D', 'B', 'D', 'B'],
        ['D', 'D', 'E', 'B', 'D'],
        ['D', 'D', 'B', 'B', 'B']],

       [['D', 'D', 'B', 'B', 'B'],
        ['B', 'B', 'D', 'D', 'B'],
        ['D', 'B', 'D', 'A', 'B']]], dtype=object)